import "s/globals.css";
import "s/reset.css";
import "s/layout.css";
import s from "./layout.module.scss";
import { Inter } from "next/font/google";
import Navbar from "./components/Navbar";

const inter = Inter({ subsets: ["latin"] });
export const metadata = {
	title: "Coffee App",
	description: "Generated by create next app"
};

export default function RootLayout({ children }) {
	return (
		<html lang="en">
			<body className={inter.className}>
				<div className={s.pageWrap}>
					<div className={s.container}>
						<div className={s.row}>
							<div className={s.column}>
								<Navbar />
								{children}
							</div>
						</div>
					</div>
				</div>
			</body>
		</html>
	);
}
