// FONT AWESOME CONFIG
import { config } from "@fortawesome/fontawesome-svg-core";
import "@fortawesome/fontawesome-svg-core/styles.css";
config.autoAddCss = false;
// STYLES
import "./reset.css";
import s from "./layout.module.scss";
// FONT
import { Inter } from "next/font/google";
// COMPONENTS
import Navbar from "./components/Navbar";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
	title: "Coffee App",
	description: "Generated by create next app",
};

export default function RootLayout({ children }) {
	return (
		<html lang='en'>
			<body className={inter.className}>
				<Navbar />
				<div className={s.pageWrap}>{children}</div>
			</body>
		</html>
	);
}
